#!/usr/bin/env bash
# Install and setup nginx into the server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo 'School' | sudo tee /var/www/html/index.html
